[package]
name = "joueur"
version = "0.1.0"
authors = ["Adam Gausmann <agausmann@fastmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
structopt = "0.3.7"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
