[package]
name = "joueur"
version = "0.1.0"
authors = ["Adam Gausmann <agausmann@fastmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.97"
serde_derive = "1.0.97"
serde_json = { version = "1.0.40", features = ["raw_value"] }
